# Generated by Django 4.2.3 on 2023-07-26 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_purchasemaster_purchasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('customer_card_no', models.TextField()),
                ('customer_name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('contact_no', models.TextField(blank=True, null=True)),
                ('discount_percent', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),

    ]
